name: Check SDK updates for ECS
on:
  schedule:
    - cron: "14 23 * * *"
  workflow_dispatch:

jobs:
  check:
    name: Check SDK updates
    runs-on: ubuntu-latest
    steps:
      - name: Check out code
        uses: actions/checkout@v3
        with:
          ref: v1

      - name: Check SDK updates for ECS
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          ./scripts/check-sdk-updates.sh
